let decache = require('decache');
let AllureReporter = require('jasmine-allure-reporter');
let data = require("../Data/data.js");
let loginPage = require("../Pages/loginPage.js");
let inboxPage = require("../Pages/inboxPage.js");
let chance = require('chance');
chance = new chance();

//generate random title
let RandomTitle = chance.string({length: 7});

describe('This is first protractor test which', function () {
    beforeEach(function () {
        loginPage.open()
    });

    it("should send email and verify Sent email", function () {

        loginPage.logIn(data.senderEmail, data.PassOne);//log in gmail via 1st user
        inboxPage.createNewDraft();//create new message
        inboxPage.typeReceiverEmail(data.receiverEmail);//type receiver
        inboxPage.typeTitle(RandomTitle);//type email title
        inboxPage.typeDescription(data.BodyText);//type email description
        inboxPage.send();
        inboxPage.openSentFolder();
        inboxPage.createdEmailCheck(RandomTitle);//verify if header equal to generated one, if so - verify if body is equal to template
    });

    it('should check presence of email sent from account 1', function () {
        loginPage.logIn(data.receiverEmail, data.PassTwo);//log in gmail via 2nd user
        inboxPage.checkForRequiredEmail(RandomTitle, data.senderName, data.BodyText);//verify if email, generated by user 1, was received
    });

    afterEach(function () {
        decache("../Data/data.js");
        decache("../Pages/loginPage.js");
        decache("../Pages/inboxPage.js");
        browser.restart();
        data = require("../Data/data.js");
        loginPage = require("../Pages/loginPage.js");
        inboxPage = require("../Pages/inboxPage.js");
    })
});